// Generated by CoffeeScript 1.12.4
var Runner, path;

path = require("path");

Runner = require("./runner");

exports.test = function(args) {
  var mod, modName;
  modName = args._.shift() || ".";
  mod = lotus.modules.load(modName);
  log.moat(1);
  log.gray.dim("Testing: ");
  log.green(lotus.relative(mod.path));
  log.moat(1);
  return mod.load(["config"]).then(function() {
    var needsCoffee, pattern;
    try {
      if (mod.spec == null) {
        mod.spec = "spec";
      }
    } catch (error) {}
    if (!mod.spec) {
      throw Error("Module named '" + mod.name + "' must define its `spec`!");
    }
    needsCoffee = mod.hasPlugin("lotus-coffee");
    pattern = path.join(mod.spec, "**", "*.");
    pattern += needsCoffee ? "coffee" : "js";
    return mod.crawl(pattern, {
      ignored: "**/{.git,node_modules}/**"
    }).then(function(files) {
      var runner;
      if (files.length === 0) {
        log.moat(1);
        log.red("Error: ");
        log.white("No tests were found.");
        log.moat(1);
        return;
      }
      if (needsCoffee) {
        require("coffee-script/register");
      }
      runner = Runner({
        bench: args.bench,
        suite: args.suite,
        reporter: args.reporter
      });
      return runner.start(files.map(function(file) {
        return file.path;
      }));
    });
  });
};
