// Generated by CoffeeScript 1.12.4
var Runner, path;

path = require("path");

Runner = require("./runner");

exports.test = function(args) {
  var mod, modName;
  modName = args._.shift() || ".";
  mod = lotus.modules.load(modName);
  log.moat(1);
  log.gray.dim("Testing: ");
  log.green(lotus.relative(mod.path));
  log.moat(1);
  return mod.load(["config"]).then(function() {
    var pattern;
    try {
      if (mod.spec == null) {
        mod.spec = "spec";
      }
    } catch (error) {}
    if (!mod.spec) {
      throw Error("Module named '" + mod.name + "' must define its `spec`!");
    }
    pattern = path.join(mod.spec, "**", "*.{js,coffee}");
    return mod.crawl(pattern, {
      ignored: "**/{.git,node_modules}/**"
    }).then(function(files) {
      var exts, filePaths, runner;
      if (files.length === 0) {
        log.moat(1);
        log.red("Error: ");
        log.white("No tests were found.");
        log.moat(1);
        return;
      }
      exts = {};
      filePaths = files.map(function(file) {
        var ext;
        ext = file.extension;
        if (!exts.hasOwnProperty(ext)) {
          exts[ext] = true;
        }
        return file.path;
      });
      if (exts[".coffee"]) {
        require("coffee-script/register");
      }
      runner = Runner({
        bench: args.bench,
        suite: args.suite,
        reporter: args.reporter
      });
      return runner.start(filePaths);
    });
  });
};
