// Generated by CoffeeScript 2.0.0-alpha1
exports.globalDependencies = ["lotus-watch"];

exports.initCommands = function() {
  return {
    test: function() {
      return require("./cli");
    }
  };
};
